name: cycle_10
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true # Add this line

  assets:
    - assets/images/
    - assets/fonts/
    - assets/files/

  fonts:
    - family: El Messiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
        - asset: assets/fonts/ElMessiri-Medium.ttf
        - asset: assets/fonts/ElMessiri-Regular.ttf
